version: "3"

services:
  postgres-db:
    image: postgres:alpine
    restart: always
    container_name: baseless-postgresql
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      # PGDATA: /data/postgres
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - POSTGRES_DB=${DATA_BASE}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
      # - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: baseless-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-custompassword}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./docker-volumes/pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
